# Generated by Django 2.1.2 on 2018-10-11 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='difficulty_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'interview_difficulty',
            },
        ),
        migrations.CreateModel(
            name='examination_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField(default=180)),
            ],
            options={
                'db_table': 'interview_examination',
            },
        ),
        migrations.CreateModel(
            name='examination_sub_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('examination_id', models.IntegerField()),
                ('result', models.IntegerField(default=-1)),
            ],
            options={
                'db_table': 'interview_examination_sub',
            },
        ),
        migrations.CreateModel(
            name='language_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('lname', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'interview_language',
            },
        ),
        migrations.CreateModel(
            name='problem_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('time_limit', models.IntegerField(default=1000)),
                ('memory_limit', models.IntegerField(default=128)),
                ('can_exam', models.BooleanField(default=False)),
                ('submission_number', models.BigIntegerField(default=0)),
                ('accepted_number', models.BigIntegerField(default=0)),
                ('difficulty', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interview.difficulty_model')),
                ('languages', models.ManyToManyField(to='interview.language_model')),
            ],
            options={
                'db_table': 'interview_problem',
            },
        ),
        migrations.CreateModel(
            name='submission_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('problem_id', models.IntegerField()),
                ('examination_sub_id', models.IntegerField()),
                ('examination_id', models.IntegerField()),
                ('language', models.CharField(max_length=64)),
                ('code', models.TextField()),
                ('state', models.IntegerField(default=0)),
                ('res', models.IntegerField(default=0)),
                ('cpu', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interview_submission',
            },
        ),
        migrations.CreateModel(
            name='tag_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'interview_tag',
            },
        ),
        migrations.AddField(
            model_name='problem_model',
            name='tags',
            field=models.ManyToManyField(to='interview.tag_model'),
        ),
        migrations.AddField(
            model_name='examination_sub_model',
            name='submissions',
            field=models.ManyToManyField(to='interview.submission_model'),
        ),
        migrations.AddField(
            model_name='examination_model',
            name='subs',
            field=models.ManyToManyField(to='interview.examination_sub_model'),
        ),
    ]
